on:
  push:
    branches:
      - 'add-choco-pkg'
      - 'main'

  workflow_dispatch:
    inputs:
      version:
        description: Version released e.g. v0.10.2
        #required: true
        default: 'v0.10.2'

jobs:
  publish-to-choco:
    runs-on: ubuntu-latest #windows-latest
    env:
      PACKAGE_PATH: $RUNNER_TEMP/chocolatey
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate package files
        shell: pwsh
        run: |
          $PkgPath = Join-Path $ENV:RUNNER_TEMP 'chocolatey'
          if (Test-Path -Path $PkgPath) { Remove-Item $PkgPath -Force -Confirm:$False | Out-Null }
          Copy-Item -Path 'scripts/chocolatey' -Destination $PkgPath -Recurse -Confirm:$False

          Write-Host "Hello"
          Dir ENV:
      # - name: Create package
      #   shell: pwsh
      #   run: |
      #     $PkgPath = Join-Path $ENV:RUNNER_TEMP 'chocolatey'
      #     Push-Location $PkgPath
      #     choco pack
