on:
  push:
    branches:
      - 'add-choco-pkg'
      - 'main'

  workflow_dispatch:
    inputs:
      version:
        description: Version released e.g. v0.10.2
        #required: true
        default: 'v0.10.2'

jobs:
  publish-to-choco:
    runs-on: windows-latest
    env:
      PACKAGE_PATH: $RUNNER_TEMP/chocolatey
    steps:
      - name: Generate package
        shell: pwsh
        run: |
          Write-Host "Hello"
          Dir ENV:
