on:
  push:
    branches:
      - 'add-choco-pkg'
      - 'main'

  workflow_dispatch:
    inputs:
      version:
        description: Version released e.g. v0.10.2
        #required: true
        default: 'v0.10.2'

jobs:
  publish-to-choco:
    runs-on: ubuntu-latest #windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate package files
        shell: pwsh
        env:
          RELEASE_VERSION: 'v0.10.2'
        run: |
          $PkgPath = Join-Path $ENV:RUNNER_TEMP 'chocolatey'
          if (Test-Path -Path $PkgPath) { Remove-Item $PkgPath -Force -Confirm:$False | Out-Null }
          Copy-Item -Path 'scripts/chocolatey' -Destination $PkgPath -Recurse -Confirm:$False
          Push-Location $PkgPath

          $Version = $ENV:RELEASE_VERSION.replace('v','')
          $URL = "https://github.com/coder/coder/releases/download/v$Version/coder_$Version_windows_amd64.zip"

          # Download it
          $ZipFile = 'tools/coder_windows_amd64.zip'
          Invoke-WebRequest -URI $URL -UseBasicParsing -OutFile $ZipFile
          $SHA256 = (Get-FileHash -Path $ZipFile -Algorithm SHA256).Hash
          Write-Host "Hash is $SHA256"

          # Munge Version
          $Content = (Get-Content -Path "coder.nuspec" -Raw).Replace('VERSION',$Version)
          Set-Content -Path "coder.nuspec" -Value $Content -Force -Confirm:$false

          Write-Host "Hello"
          Dir ENV:

      - name: DEBUG
        shell: pwsh
        run: |
          $PkgPath = Join-Path $ENV:RUNNER_TEMP 'chocolatey'

          Write-Host "---- nuspec"
          Get-Content -Path "$PkgPath/coder.nuspec" -Raw
          Write-Host "---- tools"
          Get-Content -Path "$PkgPath/tools/chocolatey-install.ps1" -Raw

      # - name: Create package
      #   shell: pwsh
      #   run: |
      #     $PkgPath = Join-Path $ENV:RUNNER_TEMP 'chocolatey'
      #     Push-Location $PkgPath
      #     choco pack
